backend:
  name: github
  repo: decidim/decidim.org
  branch: content/update

media_folder: "source/blog/images"

collections:
  - name: "post-en"
    label: "Post (EN)"
    folder: "source/blog/en"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Draft", name: "published", widget: "hidden", default: "false"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "post-es"
    label: "Post (ES)"
    folder: "source/blog/es"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Draft", name: "published", widget: "hidden", default: "false"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "post-ca"
    label: "Post (CA)"
    folder: "source/blog/ca"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Draft", name: "published", widget: "hidden", default: "false"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Used By"
    name: "usedby"
    create: true
    files:
      - label: "Used By"
        name: "usedby"
        file: "data/cities.yml"
        fields:
          - {label: Name, name: name, widget: string}
          - {label: URL, name: url, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Type, name: type, widget: "select", options: ["city", "org", "region"]}
          - {label: Home, name: home, widget: boolean}
  - label: "Used By test"
    name: "usedbytest"
    create: true
    files:
      - label: "Used By"
        name: "usedby"
        file: "data/citiestest.yml"
        fields:
          - {label: Name, name: name, widget: string}
          - {label: URL, name: url, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Type, name: type, widget: "select", options: ["city", "org", "region"]}
          - {label: Home, name: home, widget: boolean}
  - label: "FAQs"
    name: "faqs"
    create: true
    files:
      - label: "FAQ questions"
        name: "faqs"
        file: "data/faqs.yml"
        fields:
          - label: EN
            name: en
            widget: list
            fields:
              - {label: question, name: question, widget: string}
              - {label: answer, name: answer, widget: string}
          - label: ES
            name: es
            widget: list
            fields:
              - {label: question, name: question, widget: string}
              - {label: answer, name: answer, widget: string}
          - label: CA
            name: ca
            widget: list
            fields:
              - {label: question, name: question, widget: string}
              - {label: answer, name: answer, widget: string}
