backend:
  name: github
  repo: decidim/decidim.org
publish_mode: editorial_workflow
media_folder: "source/uploads"
collections:
  - name: "post-en"
    label: "Post (EN)"
    folder: "source/blog/en"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Draft", name: "published", widget: "hidden", default: "false"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "post-es"
    label: "Post (ES)"
    folder: "source/blog/es"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Draft", name: "published", widget: "hidden", default: "false"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "post-ca"
    label: "Post (CA)"
    folder: "source/blog/ca"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Draft", name: "published", widget: "hidden", default: "false"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: Installation
    label: Installation
    format: yml
    extension: yml
    folder: data/installations/
    create: true
    fields:
      - {label: Title, name: title, widget: string, required: true}
      - {label: URL, name: url, widget: string, required: true}
      - {label: Image, name: image, widget: image, required: true}
      - {label: Type, name: type, widget: "select", options: ["city", "org", "region"], required: true}
      - label: "Priority"
        name: "priority"
        widget: "number"
        default: 2
        valueType: "int"
        min: 1
        max: 101
        step: 2
        hint: Larger number is more priority (100 is Barcelona)
  - label: "FAQs"
    name: "faqs"
    format: yml
    extension: yml
    folder: data/faqs/
    create: true
    fields:
      - {label: "Question EN", name: title, widget: string, required: true}
      - {label: "Answer EN", name: answer_en, widget: markdown}
      - {label: "Question ES", name: question_es, widget: string}
      - {label: "Answer ES", name: answer_es, widget: markdown}
      - {label: "Question CA", name: question_ca, widget: string}
      - {label: "Answer CA", name: answer_ca, widget: markdown}
      - label: "Priority"
        name: "priority"
        widget: "number"
        default: 2
        valueType: "int"
        min: 1
        max: 101
        step: 2
        hint: Larger number is more priority (first on list)
