backend:
  name: github
  repo: decidim/decidim.org
media_folder: "source/uploads"
public_folder: "/uploads/"
collections:
  - name: "post-en"
    label: "Post (EN)"
    folder: "source/blog/en"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "html.md"
    format: "frontmatter"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "post-es"
    label: "Post (ES)"
    folder: "source/blog/es"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "html.md"
    format: "frontmatter"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "post-ca"
    label: "Post (CA)"
    folder: "source/blog/ca"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "html.md"
    format: "frontmatter"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "Installation"
    label: "Installation"
    format: yml
    extension: yml
    folder: data/installations/
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "URL", name: "url", widget: "string", required: true}
      - {label: "Image", name: "image", widget: "image", required: true}
      - {label: "Type", name: "type", widget: "select", options: ["city", "org", "region"], required: true}
      - label: "Priority"
        name: "priority"
        widget: "number"
        default: 2
        valueType: "int"
        min: 1
        max: 101
        step: 2
        hint: Larger number is more priority (100 is Barcelona)
      - {label: "Home", name: "home", widget: "boolean", hint: "Is it going to be published on homepage?"}
  - name: "Module"
    label: "Module"
    format: yml
    extension: yml
    folder: data/modules/
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "URL", name: "url", widget: "string", required: true}
      - {label: "Image", name: "image", widget: "image", required: true}
      - {label: "Description", name: "description", widget: "text", required: true}
      - {label: "Type", name: "type", widget: "select", options: ["official", "community", "auth"], required: true}
  - label: "FAQs"
    name: "faqs"
    format: yml
    extension: yml
    folder: data/faqs/
    create: true
    fields:
      - {label: "Question EN", name: title, widget: string, required: true}
      - {label: "Answer EN", name: answer_en, widget: markdown}
      - {label: "Question ES", name: question_es, widget: string}
      - {label: "Answer ES", name: answer_es, widget: markdown}
      - {label: "Question CA", name: question_ca, widget: string}
      - {label: "Answer CA", name: answer_ca, widget: markdown}
      - label: "Priority"
        name: "priority"
        widget: "number"
        default: 2
        valueType: "int"
        min: 1
        max: 101
        step: 2
        hint: Larger number is more priority (first on list)
  - label: "Testimonial"
    name: "testimonials"
    format: yml
    extension: yml
    folder: data/testimonials/
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Image", name: "image", widget: "image", required: true}
      - {label: "Organization EN", name: organization_en, widget: "string", required: true}
      - {label: "Quote EN", name: "quote_en", widget: "text", required: true}
      - {label: "Organization ES", name: organization_es, widget: "string", required: true}
      - {label: "Quote ES", name: "quote_es", widget: "text", required: true}
      - {label: "Organization CA", name: organization_ca, widget: "string", required: true}
      - {label: "Quote CA", name: "quote_ca", widget: "text", required: true}
